from typing import Literal, Tuple

from flax import nnx

from scm.interfaces import ModelFn, ProgVars, DiagVars

METHODS = Literal["euler", "rk2", "rk4"]


def init_time_stepper(model: ModelFn, dt: float, method: METHODS) -> ModelFn:
    @nnx.jit
    def _euler(state: ProgVars, **kwargs) -> Tuple[ProgVars, DiagVars]:
        """Euler integration"""
        tends, diag = model(state, **kwargs)
        state_next = ProgVars(
            u=state.u + dt * tends.u,
            v=state.v + dt * tends.v,
            th=state.th + dt * tends.th,
            q=state.q + dt * tends.q,
        )
        return state_next, diag

    @nnx.jit
    def _rk2(state: ProgVars, **kwargs) -> Tuple[ProgVars, DiagVars]:
        """2nd-order Runge-Kutta integration
        ATTENTION! Generated by Copilot, not tested!
        """
        k1, diag1 = model(state, **kwargs)
        state_k2 = ProgVars(
            u=state.u + 0.5 * dt * k1.u,
            v=state.v + 0.5 * dt * k1.v,
            th=state.th + 0.5 * dt * k1.th,
            q=state.q + 0.5 * dt * k1.q,
        )
        k2, diag2 = model(state_k2, **kwargs)
        state_next = ProgVars(
            u=state.u + dt * k2.u,
            v=state.v + dt * k2.v,
            th=state.th + dt * k2.th,
            q=state.q + dt * k2.q,
        )
        _, diag = model(state_next, **kwargs)  # Recompute diagnostics for the next state
        return state_next, diag

    @nnx.jit
    def _rk4(state: ProgVars, **kwargs) -> Tuple[ProgVars, DiagVars]:
        """4th-order Runge-Kutta integration"""
        k1, diag1 = model(state, **kwargs)
        state_k2 = ProgVars(
            u=state.u + 0.5 * dt * k1.u,
            v=state.v + 0.5 * dt * k1.v,
            th=state.th + 0.5 * dt * k1.th,
            q=state.q + 0.5 * dt * k1.q,
        )
        k2, diag2 = model(state_k2, **kwargs)
        state_k3 = ProgVars(
            u=state.u + 0.5 * dt * k2.u,
            v=state.v + 0.5 * dt * k2.v,
            th=state.th + 0.5 * dt * k2.th,
            q=state.q + 0.5 * dt * k2.q,
        )
        k3, diag3 = model(state_k3, **kwargs)
        state_k4 = ProgVars(
            u=state.u + dt * k3.u,
            v=state.v + dt * k3.v,
            th=state.th + dt * k3.th,
            q=state.q + dt * k3.q,
        )
        k4, diag4 = model(state_k4, **kwargs)

        state_next = ProgVars(
            u=state.u + (dt / 6) * (k1.u + 2 * k2.u + 2 * k3.u + k4.u),
            v=state.v + (dt / 6) * (k1.v + 2 * k2.v + 2 * k3.v + k4.v),
            th=state.th + (dt / 6) * (k1.th + 2 * k2.th + 2 * k3.th + k4.th),
            q=state.q + (dt / 6) * (k1.q + 2 * k2.q + 2 * k3.q + k4.q),
        )
        _, diag = model(state_next, **kwargs)  # Recompute diagnostics for the next state

        return state_next, diag

    if method == "euler":
        return _euler
    elif method == "rk2":
        return _rk2
    elif method == "rk4":
        return _rk4
    else:
        raise NotImplementedError
